<?xml version="1.0"?>
<package format="3">
  <name>adma_core_lib</name>
  <version>0.0.0</version>
  <description>Collection of some basic functionality for using ADMA with ROS</description>
  <maintainer email="rico.schillings@hs-offenburg.de">Rico Schillings</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>tinyxml2</depend>
  <depend>tinyxml2_vendor</depend>
  <depend>geometry_msgs</depend>
  <depend>adma_ros_driver_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <!-- <test_depend>ament_cmake_clang_format</test_depend> -->
  <!-- <test_depend>ament_cmake_uncrustify</test_depend>
  <test_depend>ament_cmake_cppcheck</test_depend>
  <test_depend>ament_cmake_cpplint</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend> -->
  
  

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>
