# accelerations body poi (in g)
geometry_msgs/Vector3 acc_body

# acceleration horizontal poi (in g)
geometry_msgs/Vector3 acc_hor

# invpath radius (in 1/m)
float64 inv_path_radius

# side slip (in deg)
float64 side_slip_angle

# distance traveled (in m)
float64 dist_trav

# ins position height poi(msl)
float64 ins_height

# ins position absolute (in deg)
float64 ins_lat_abs
float64 ins_lon_abs

# ins position relative (in m)
float64 ins_pos_rel_x
float64 ins_pos_rel_y

# ins velocity horizontal poi (in m/s)
geometry_msgs/Vector3 ins_vel_hor