genesys:
  gsda_server:
    ros__parameters:
      frequency: 100
      gsda_file: '/home/$USER/$ROS2_WS/data/$FILENAME.gsda'
      frame_ids:
        navsatfix: 'gnss_link'
        imu: 'imu_link'
        adma: 'adma'
        adma_status: 'adma_status'
        raw_data: 'data_raw'
        odometry_pose_id: 'adma' # header.frame_id (basicly could be a "name" of desired POI)
        odometry_twist_id: 'odometry' # odometry.child_frame_id
      odometry_yaw_offset: 0.0 # in degrees
      publish_tf: False # can be used for debugging and visualization in Rviz2