genesys:
  adma_ros2_driver:
    ros__parameters:
      destination_ip: '127.0.0.1'
      destination_port: 1040
      use_performance_check: False
      protocol_version: 'v3.3.4'
      mode: 'default' # available modes are: default/replay
      frame_ids:
        navsatfix: 'gnss_link'
        imu: 'imu_link'
        adma: 'adma'
        adma_status: 'adma_status'
        raw_data: 'data_raw'
  gsdb_server:
    ros__parameters:
      ip_address: '127.0.0.1'
      port: 1040
      frequency: 100
      protocol_version: 'v3.3.4'
      gsdb_file: '/home/rschilli/Documents/GeneSys/rosbags_ros2/ROS2_Arbeitsplatz/raw_data.gsdb'