genesys:
  adma_ros2_driver:
    ros__parameters:
      destination_ip: '127.0.0.1'
      destination_port: 1040
      use_performance_check: False
      frame_ids:
        navsatfix: 'gnss_link'
        imu: 'imu_link'
        adma: 'adma'
        adma_status: 'adma_status'
        raw_data: 'data_raw'
        odometry_pose_id: 'adma' # header.frame_id (basicly could be a "name" of desired POI)
        odometry_twist_id: 'odometry' # odometry.child_frame_id
      odometry_yaw_offset: 0.0 # in degrees
  gsdb_server:
    ros__parameters:
      admanet_ip_address: '127.0.0.1'
      admanet_port: 11040
      contains_addondelta: True
      addondelta_ip_address: '127.0.0.1'
      addondelta_port: 1025
      frequency: 100
      gsdb_file: '/home/rschilli/Documents/GeneSys/Github_Issues/Messdaten_Delta_1-1/Delta_ADMAnet_beides.gsdb'
      # gsdb_file: '/home/rschilli/Documents/GeneSys/Github_Issues/Messdaten_Delta_1-1/Only_Delta1-1.gsdb'
  adma_ros2_delta_driver:
    ros__parameters:
      destination_ip: '127.0.0.1'
      destination_port: 1025
      protocol_version: 'v7.0'
