# accelerations body poi
# acc in g
int16 acc_body_x
int16 acc_body_y
int16 acc_body_z
float64 f_acc_body_x
float64 f_acc_body_y
float64 f_acc_body_z

# acceleration horizontal poi
# acc in g
int16 acc_hor_x
int16 acc_hor_y
int16 acc_hor_z
float64 f_acc_hor_x
float64 f_acc_hor_y
float64 f_acc_hor_z

# miscellaneous_poi
# invpath radius in 1/m
int16 inv_path_radius
float64 f_inv_path_radius
# side slip in degrees
int16 side_slip_angle
float64 f_side_slip_angle
# dis_trav in m
uint32 dist_trav
float64 f_dist_trav

# ins position height poi(msl)
int32 ins_height
float64 f_ins_height

# ins position absolute
# position in deg
int32 ins_lat_abs
int32 ins_lon_abs
float64 f_ins_lat_abs
float64 f_ins_lon_abs

# ins position relative
# position in m
int32 ins_lat_rel
int32 ins_lon_rel
float64 f_ins_lat_rel
float64 f_ins_lon_rel

# ins velocity horizontal poi
# velocity in m/s
int16 ins_vel_hor_x
int16 ins_vel_hor_y
int16 ins_vel_hor_z
float64 f_ins_vel_hor_x
float64 f_ins_vel_hor_y
float64 f_ins_vel_hor_z