name: ROS2 CI

on:
  push:
    branches: [ ros2_dev ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # ros_distro: [ humble, iron, rolling ]
        ros_distro: [ humble ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: "adma_ros_driver_msgs" # empty entry for building all packages from repo
          target-ros2-distro: ${{ matrix.ros_distro }}
